name: Go
on: push

jobs:
  go-lint:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --timeout 5m

  go-test-build:
    name: test and build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.5.2