name: Go
on: push

jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --timeout 5m