name: Go
on: push

jobs:
  go-lint:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --timeout 5m

  go-test:
    name: test
    needs: [lint]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
      - name: Go Test
        run: go test ./...